# Generated by Django 2.1.3 on 2018-11-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
    ]
