# Generated by Django 2.1.3 on 2018-11-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20181129_1940'),
    ]

    operations = [
    ]
