# Generated by Django 2.1.3 on 2018-12-04 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_uploadfile'),
    ]

    operations = [
    ]
