# Generated by Django 2.1.3 on 2018-12-04 00:07

from django.db import migrations, models
import django.utils.timezone
import uploader.utils


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_auto_20181204_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='last_accessed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=uploader.utils.generate_random_folder),
        ),
    ]
